### ISSUE TITLE
missing files?

### ISSUE THREAD

**Issue by royjara** [samsad35/source-filter-vae#3]
Was trying to run the examples but was unable to even import. Getting this error
`ModuleNotFoundError: No module named 'sf_vae.sf_vae.f0_detection.f0_estimation'`

I checked the files and don't see any module/methods under `f0_detection`

Can you help me solve this? thanks!

**Comment by samsad35** [comment]
Ah yes, I'm sorry this line is for another independent project, you can however comment this line. Tell me if it works, thank you.

**Comment by royjara** [comment]
Indeed, commenting that out works. Thanks!
